version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: Postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mediscreenPatient
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  microservice-patient:
    container_name: microservice-patient
    build: ./microservice-patient
    ports:
      - "9001:9001"
    depends_on:
      - postgresql

  microservice-note:
    container_name: microservice-note
    build: ./microservice-note
    ports:
      - "9002:9002"
    depends_on:
      - mongodb

  microservice-diabete:
    container_name: microservice-diabete
    build: ./microservice-diabete
    ports:
      - "9003:9003"
    depends_on:
      - postgresql

  microservice-clientui:
    container_name: microservice-clientui
    build: ./microservice-clientui
    ports:
      - "9000:9000"

volumes:
  pgdata:
  mongodata:
