logging.level.org.springframework=INFO
spring.application.name=microservice-notes
server.port=9002

spring.data.mongodb.uri=mongodb://root:root@mongodb:27017/mediscreenNote?authSource=admin
spring.datasource.username=root
spring.datasource.password=root
